/**
 * Mint Ambassador card layout configuration.
 *
 * The template currently in `templates/` is a STAND-IN, generated by
 * `scripts/generate-card-template.mjs`, because the real designed card has not been
 * supplied yet. The coordinates below are calibrated against that stand-in.
 *
 * REPLACING THE TEMPLATE:
 *  1. Flatten the real design to `templates/${AMBASSADOR_CARD_TEMPLATE_FILE}`
 *     (`pdftoppm -jpeg -r 150 design.pdf out` for a PDF, or export straight to JPG/PNG
 *     from Figma/PSD/AI). It must contain everything static -- branding, title, field
 *     labels -- and leave the three value slots empty.
 *  2. Set CARD_WIDTH/CARD_HEIGHT to the new image's real pixel dimensions.
 *     `generateAmbassadorCardJpg` throws if they disagree rather than silently
 *     stamping text in the wrong place.
 *  3. Re-measure the three boxes against the real file. Do not carry these numbers
 *     over -- they describe the stand-in's layout, nothing else.
 *  4. Check the result at `/dev/ambassador-card-preview` (auth required) and run
 *     `npm test`, which asserts the stamped name actually lands inside NAME_BOX.
 *
 * Coordinates are PIXELS from the TOP-LEFT, and `y` is the text BASELINE (SVG
 * convention). Note this is the opposite origin from the standee's pdf-lib boxes,
 * which measure from the bottom-left.
 */

export interface TextBox {
  /** Left edge of the text run. */
  x: number;
  /** Text baseline, measured down from the top of the image. */
  y: number;
  /** Space available before the text would collide with the panel edge. */
  width: number;
  fontSize: number;
  fontWeight: number;
  color: string;
}

export const AMBASSADOR_CARD_TEMPLATE_FILE = "ambassador-card-background.jpg";

/**
 * Must match the font the template itself was rendered with, and must be a font that
 * exists on the DEPLOYMENT host -- sharp renders SVG text through the system's
 * fontconfig, so a host with no fonts installed produces a card with blank value
 * slots. `tests/ambassador.test.ts` asserts stamped text actually changes pixels,
 * which is what catches that in CI rather than in a student's LinkedIn post.
 */
export const FONT_STACK = "Liberation Sans, DejaVu Sans, sans-serif";

/** 4:5 portrait -- Instagram's optimal feed post size. */
export const CARD_WIDTH = 1080;
export const CARD_HEIGHT = 1350;

/** Panel rows are 183 px apart; each value sits 133 px below its row's top edge. */
export const NAME_BOX: TextBox = {
  x: 140, y: 645, width: 800, fontSize: 54, fontWeight: 700, color: "#ffffff",
};
export const UNIVERSITY_BOX: TextBox = {
  x: 140, y: 828, width: 800, fontSize: 40, fontWeight: 600, color: "#ffffff",
};
export const BATCH_BOX: TextBox = {
  x: 140, y: 1011, width: 800, fontSize: 38, fontWeight: 600, color: "#dcfce7",
};

/**
 * Below this the text is too small to read on a phone, so an absurdly long value is
 * truncated instead of being shrunk further.
 */
export const MIN_FONT_SIZE = 26;
